name: TeaMC
version: '${project.version}'
main: io.github.kraksy.teamc.TeaMC
api-version: 1.19
authors: [ krek ]
description: plugins for tea mc
commands:
  duh:
    description: duh
    usage: /<command>
  anvil:
    description: portable anvil
    usage: /<command>
  gemGui:
    description: gem gui
    usage: /<command>
